# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/url_download_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(735, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_video_url = QtWidgets.QLabel(self.centralwidget)
        self.label_video_url.setGeometry(QtCore.QRect(20, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_video_url.setFont(font)
        self.label_video_url.setObjectName("label_video_url")
        self.lineEdit_url = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_url.setGeometry(QtCore.QRect(20, 60, 521, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_url.setFont(font)
        self.lineEdit_url.setObjectName("lineEdit_url")
        self.pushButton_load = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_load.setGeometry(QtCore.QRect(550, 60, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_load.setFont(font)
        self.pushButton_load.setObjectName("pushButton_load")
        self.graphicsView_video_thumbnail = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_video_thumbnail.setGeometry(QtCore.QRect(20, 100, 341, 221))
        self.graphicsView_video_thumbnail.setObjectName("graphicsView_video_thumbnail")
        self.label_video_description = QtWidgets.QLabel(self.centralwidget)
        self.label_video_description.setGeometry(QtCore.QRect(370, 100, 341, 211))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_video_description.setFont(font)
        self.label_video_description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_video_description.setObjectName("label_video_description")
        self.comboBox_streams = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_streams.setGeometry(QtCore.QRect(20, 340, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox_streams.setFont(font)
        self.comboBox_streams.setObjectName("comboBox_streams")
        self.pushButton_download = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_download.setGeometry(QtCore.QRect(490, 490, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_download.setFont(font)
        self.pushButton_download.setObjectName("pushButton_download")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 512, 451, 21))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_info = QtWidgets.QLabel(self.centralwidget)
        self.label_info.setGeometry(QtCore.QRect(374, 445, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_info.setFont(font)
        self.label_info.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_info.setObjectName("label_info")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 735, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YouTube VA Downloader"))
        self.label_video_url.setText(_translate("MainWindow", "Video URL"))
        self.lineEdit_url.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt; font-style:italic;\">Enter the video url here and press load in order to get available video, audio formats.</span></p></body></html>"))
        self.pushButton_load.setText(_translate("MainWindow", "Load"))
        self.label_video_description.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_download.setText(_translate("MainWindow", "Download"))
        self.label_info.setText(_translate("MainWindow", "TextLabel"))
